
package clientws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioService", targetNamespace = "http://servicio/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "capitalize", targetNamespace = "http://servicio/", className = "clientws.Capitalize")
    @ResponseWrapper(localName = "capitalizeResponse", targetNamespace = "http://servicio/", className = "clientws.CapitalizeResponse")
    @Action(input = "http://servicio/ServicioService/capitalizeRequest", output = "http://servicio/ServicioService/capitalizeResponse")
    public String capitalize(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
