
package clientws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioServiceService", targetNamespace = "http://servicio/", wsdlLocation = "file:/work/ServicioService.wsdl")
public class ServicioServiceService
    extends Service
{

    private final static URL SERVICIOSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOSERVICESERVICE_EXCEPTION;
    private final static QName SERVICIOSERVICESERVICE_QNAME = new QName("http://servicio/", "ServicioServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/work/ServicioService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOSERVICESERVICE_WSDL_LOCATION = url;
        SERVICIOSERVICESERVICE_EXCEPTION = e;
    }

    public ServicioServiceService() {
        super(__getWsdlLocation(), SERVICIOSERVICESERVICE_QNAME);
    }

    public ServicioServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOSERVICESERVICE_QNAME, features);
    }

    public ServicioServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOSERVICESERVICE_QNAME);
    }

    public ServicioServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOSERVICESERVICE_QNAME, features);
    }

    public ServicioServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioService
     */
    @WebEndpoint(name = "ServicioServicePort")
    public ServicioService getServicioServicePort() {
        return super.getPort(new QName("http://servicio/", "ServicioServicePort"), ServicioService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioService
     */
    @WebEndpoint(name = "ServicioServicePort")
    public ServicioService getServicioServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio/", "ServicioServicePort"), ServicioService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOSERVICESERVICE_EXCEPTION!= null) {
            throw SERVICIOSERVICESERVICE_EXCEPTION;
        }
        return SERVICIOSERVICESERVICE_WSDL_LOCATION;
    }

}
