/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct username {
	char username[256];
};
typedef struct username username;

#define COMUNICACION 1
#define COMUNICACIONVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define add_register_rpc 1
extern  enum clnt_stat add_register_rpc_1(username , int *, CLIENT *);
extern  bool_t add_register_rpc_1_svc(username , int *, struct svc_req *);
#define delete_register_rpc 2
extern  enum clnt_stat delete_register_rpc_1(username , int *, CLIENT *);
extern  bool_t delete_register_rpc_1_svc(username , int *, struct svc_req *);
#define existRegister_rpc 3
extern  enum clnt_stat existregister_rpc_1(username , int *, CLIENT *);
extern  bool_t existregister_rpc_1_svc(username , int *, struct svc_req *);
extern int comunicacion_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add_register_rpc 1
extern  enum clnt_stat add_register_rpc_1();
extern  bool_t add_register_rpc_1_svc();
#define delete_register_rpc 2
extern  enum clnt_stat delete_register_rpc_1();
extern  bool_t delete_register_rpc_1_svc();
#define existRegister_rpc 3
extern  enum clnt_stat existregister_rpc_1();
extern  bool_t existregister_rpc_1_svc();
extern int comunicacion_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_username (XDR *, username*);

#else /* K&R C */
extern bool_t xdr_username ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
