/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"
#include "lista.h"

registerList reglist;
bool_t
add_register_rpc_1_svc(username reg, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	*result = add_register(&reglist, reg.username);
	// Si la comunicación se realiza correcta retval es TRUE
	retval = TRUE;

	return retval;
}

bool_t
delete_register_rpc_1_svc(username reg, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	*result = delete_register(&reglist, reg.username);
	// Si la comunicación se realiza correcta retval es TRUE
	retval = TRUE;

	return retval;
}

bool_t
existregister_rpc_1_svc(username reg, int *result,  struct svc_req *rqstp)
{
	bool_t retval;

	*result = existRegister(reglist, reg.username);
	// Si la comunicación se realiza correcta retval es TRUE
	retval = TRUE;

	return retval;
}

int
comunicacion_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	return 1;
}
