/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
add_register_rpc_1(username reg, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, add_register_rpc,
		(xdrproc_t) xdr_username, (caddr_t) &reg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
delete_register_rpc_1(username reg, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, delete_register_rpc,
		(xdrproc_t) xdr_username, (caddr_t) &reg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
existregister_rpc_1(username reg, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, existRegister_rpc,
		(xdrproc_t) xdr_username, (caddr_t) &reg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
