/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"


void
comunicacion_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	username  add_register_rpc_1_reg;
	enum clnt_stat retval_2;
	int result_2;
	username  delete_register_rpc_1_reg;
	enum clnt_stat retval_3;
	int result_3;
	username  existregister_rpc_1_reg;

#ifndef	DEBUG
	clnt = clnt_create (host, COMUNICACION, COMUNICACIONVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = add_register_rpc_1(add_register_rpc_1_reg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = delete_register_rpc_1(delete_register_rpc_1_reg, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = existregister_rpc_1(existregister_rpc_1_reg, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	comunicacion_1 (host);
exit (0);
}
